### ISSUE TITLE
Linksys Velop Integration Stop working after the 2022.4.2b2 update

### ISSUE THREAD

**Issue by aAbdman** [uvjim/linksys_velop#180]
Hi
after Upgrading to the Linksys Velop 2022.4.2b2 the integration stoped working for my two separate Velops, and receive the following error:

```This error originated from a custom integration.

Logger: custom_components.linksys_velop
Source: custom_components/linksys_velop/__init__.py:199
Integration: Linksys Velop (documentation, issues)
First occurred: 02:39:25 (2 occurrences)
Last logged: 02:39:25

Unexpected error fetching linksys_velop (#############) data: 'NoneType' object has no attribute 'lower'
Unexpected error fetching linksys_velop (#############) data: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/linksys_velop/__init__.py", line 193, in _async_get_mesh_data
    previous_nodes: Set[str] = {
  File "/config/custom_components/linksys_velop/__init__.py", line 199, in <setcomp>
    dr_device.name.lower() != "mesh",
AttributeError: 'NoneType' object has no attribute 'lower'
```

Any advice?

**Comment by uvjim** [comment]
I know why it's happening, but it shouldn't be happening. I'll see if I can be more targeted in that code and resolve this.

**Comment by uvjim** [comment]
I've just pushed `b3`.  Could you give that a go please? #182 should have resolved the issue.
Let me know how you get on.

**Comment by aAbdman** [comment]
Everything looks good and normal after the b3 update👌🏼

Thank you

**Comment by uvjim** [comment]
Brilliant. I'll close this off then.
