### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by GSzabados** [uvjim/linksys_velop#198]
I have a lot of these error messages:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/linksys_velop/sensor.py:112
Integration: Linksys Velop (documentation, issues)
First occurred: 3 May 2022, 22:03:22 (6587 occurrences)
Last logged: 13:24:23

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/config/custom_components/linksys_velop/__init__.py", line 417, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 328, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 410, in state
    value = self.native_value
  File "/config/custom_components/linksys_velop/sensor.py", line 320, in native_value
    return self.entity_description.state_value(self._mesh)
  File "/config/custom_components/linksys_velop/sensor.py", line 112, in <lambda>
    state_value=lambda m: len(m.storage_available)
  File "/usr/local/lib/python3.9/site-packages/pyvelop/mesh.py", line 970, in storage_available
    "used_percent": round((partition.get("usedKB") / partition.get("availableKB")) * 100, 2),
ZeroDivisionError: division by zero

```

I guess somehow availableKB must end up being zero. No idea why.

**Comment by uvjim** [comment]
Yeah... that does seem odd.  I was just thinking of releasing the beta but I'll put some guards into pyvelop first and then release a new beta.  Shouldn't take me long.  If you can test afterwards that'd be great...

**Comment by uvjim** [comment]
Hopefully fixed in #199 

Just published 2022.5.1b5.  Can you test with that please?  We'll keep it running for a few days to make sure the logs are clean and then I'll look to release it.

**Comment by GSzabados** [comment]
Thanks @uvjim.

I have no clue why it has happened. And unfortunately I cannot check it physically at the moment, maybe something has happened with the connected drive.

I will update to that beta and test it.

**Comment by uvjim** [comment]
No problem.  Thankd for raising this.  I probably should have had the guard in from the beginning.  I know it may cause an issue with the example cards as the percentage value will now be set to None if the error occurs.  Shoudl be simple to fix but I won't see it as I don't use the storage functionality really.  There's a USB stick in the back of one node only so I could build the sensor in - it doesn't get used for anythin at all.

**Comment by uvjim** [comment]
Hi @GSzabados, are the logs looking cleaner now?  No more errors?

**Comment by uvjim** [comment]
Thanks. I'll create the release later then.
