### ISSUE TITLE
Device tracker 

### ISSUE THREAD

**Issue by musthafapa** [uvjim/linksys_velop#291]
Device tracker unavailable  after recent update

**Comment by uvjim** [comment]
Hi. Is there anything in the logs?  Have you tried reloading the integration?

**Comment by musthafapa** [comment]
Tried removing the integration and added again twice.

when I tried to reconfigure there is an unknown error message. When I enabled logging mode to single poll, the error goes away; still device tracking is not working

**Comment by musthafapa** [comment]
2022-10-03 22:38:11.400 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.2.1 for linksys_velop
File "/config/custom_components/linksys_velop/__init__.py", line 268, in async_setup_entry
File "/config/custom_components/linksys_velop/__init__.py", line 195, in async_logging_state
2022-10-05 22:34:18.397 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Linksys Velop Mesh for linksys_velop
File "/config/custom_components/linksys_velop/__init__.py", line 268, in async_setup_entry
File "/config/custom_components/linksys_velop/__init__.py", line 195, in async_logging_state

**Comment by musthafapa** [comment]
Logger: homeassistant.config_entries
Source: core.py:1685
First occurred: 10:35:13 PM (1 occurrences)
Last logged: 10:35:13 PM
Error setting up entry Linksys Velop Mesh for linksys_velop

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/linksys_velop/__init__.py", line 268, in async_setup_entry
    await async_logging_state(
  File "/config/custom_components/linksys_velop/__init__.py", line 195, in async_logging_state
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1685, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service logger.set_level

**Comment by uvjim** [comment]
Sorry, what am I looking at in the two logs?  When did each of them occur?  What's shown in the debug log file as that will help me work out what was happening at the time.

**Comment by musthafapa** [comment]
please guide me to extract log . I can follow the steps and send you

**Comment by uvjim** [comment]
Out of interest what version of HomeAssitant are you running?

**Comment by musthafapa** [comment]
Home Assistant 2022.10.0 
Supervisor 2022.09.1 
Operating System 9.0 
Frontend 20221005.0

**Comment by uvjim** [comment]
I have an idea about what might be causing this with the logging. I'll see if I can resolve it soon.

It shouldn't be causing issues with the device trackers though.

**Comment by uvjim** [comment]
I think this should be solved by #293.

The fix will reset the logging mode if the `logger` integration isn't available.  That should get you up and running without having to do anything other than uprade.

This will be included in the next release.

**Comment by uvjim** [comment]
I've released the beta in HACS now so you could upgrade to that if you want to test the fix works for you.  I've tested against my system and it seems to have been resolved.

**Comment by uvjim** [comment]
Brilliant. So all good then?

**Comment by musthafapa** [comment]
my previous comment didn't explain it. Edited now

**Comment by musthafapa** [comment]
UPDATE: I manually enabled the entity now. and now shows the device tracking.

please check why device_tracker is disabled by default

**Comment by uvjim** [comment]
> UPDATE: I manually enabled the entity now. and now shows the device tracking.
> 
> please check why device_tracker is disabled by default

The integration does not disable device trackers by default. As explained previously this is likely done by Home Assistant if it can't find a way of linking a device trackers to a device. This behaviour was introduced by Home Assistant earlier this year.
