### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by Wetzel402** [uvjim/linksys_velop#341]
HA is reporting the following error on version 2022.11.2:

```
Unexpected exception importing component custom_components.linksys_velop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/linksys_velop/__init__.py", line 28, in <module>
    from pyvelop.const import _PACKAGE_AUTHOR as PYVELOP_AUTHOR
  File "/usr/local/lib/python3.9/site-packages/pyvelop/__init__.py", line 4, in <module>
    def signal_strength_to_text(rssi: int | None) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by uvjim** [comment]
Are you by any chance using a version of Python prior to 3.10?

**Comment by Wetzel402** [comment]
I'm currently on Python 3.10.4

**Comment by uvjim** [comment]
OK.  The fault is in the upstream library.  It's a single line of code needed.  I've just made that change but will need to run through some tests as there are currently other changes that could affect the integration.

Hopefully I'll get a beta out today with the fix in.

**Comment by uvjim** [comment]
Re-opening as closed upstream but not closed in the integration.

**Comment by uvjim** [comment]
Hopefully you're not having this issue still.  I'll close this.  Feel free to re-open if it's still an issue.

**Comment by Wetzel402** [comment]
It looks like I'm receiving a slightly different error now on version 2022.12.1b1.

```
Unexpected exception importing platform custom_components.linksys_velop.switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 618, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 635, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/linksys_velop/switch.py", line 31, in <module>
    class OptionalLinksysVelopDescription:
  File "/config/custom_components/linksys_velop/switch.py", line 34, in OptionalLinksysVelopDescription
    extra_attributes: Callable | None = None
TypeError: unsupported operand type(s) for |: '_CallableType' and 'NoneType'
```

**Comment by Wetzel402** [comment]
Looking good here.  Thank you very much!
