### ISSUE TITLE
Can't remove missing device tracker

### ISSUE THREAD

**Issue by Wraith324** [uvjim/linksys_velop#439]
I have 1 repair that won't go away.   I was tracking a device and I'm guessing the MAC address changed due to private Wi-Fi addressing, which I have since turned off, but there's no way to repair this.  I get 'unknown error occurred' when I try.

![image](https://github.com/uvjim/linksys_velop/assets/44790592/ba8ffacb-f3e3-4b7f-8a55-dd46d9873195)

Here's what I have in logs:

Logger: aiohttp.server
Source: custom_components/linksys_velop/repairs.py:46
Integration: Linksys Velop ([documentation](https://github.com/uvjim/linksys_velop), [issues](https://github.com/uvjim/linksys_velop/issues))
First occurred: 5:52:48 AM (3 occurrences)
Last logged: 5:57:11 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/repairs/websocket_api.py", line 135, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linksys_velop/repairs.py", line 46, in async_step_confirm_removal
    entity_registry.async_get(entity_id=self.data.get("device_id"))
TypeError: EntityRegistry.async_get() got an unexpected keyword argument 'entity_id'

**Comment by uvjim** [comment]
I see what the error is. I'll let you know when it's fixed.

**Comment by uvjim** [comment]
@Wraith324 - I've just pushed `2023.10.1b0`. Would you be able to test this please and see if it resolves the issue?

**Comment by Wraith324** [comment]
Sure, I'll update now and try it out.

**Comment by Wraith324** [comment]
Yes, that seems to have solved it. The repair worked. 

Thank you @uvjim for the quick attention to this.

**Comment by uvjim** [comment]
No problem. It's not often I get a repair so it's easy for me to miss testing those bits properly. Feedback helps in those scenarios so, thanks.

I've got no other changes queued up to make so I'll probably release this properly next week.

**Comment by Wraith324** [comment]
Super! I loving this integration.  It's about the only thing that works presence-wise for me.
