### ISSUE TITLE
HA 2023.12.3: Platform error: device_tracker - Requirements for linksys_velop not found: ['pyvelop>=2023.9.1']. 

### ISSUE THREAD

**Issue by walking-octopus** [uvjim/linksys_velop#443]
```
## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Europe/Kiev
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 58.0 GB
disk_used | 8.4 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), Mosquitto broker (6.4.0), Node-RED (16.0.2), SQLite Web (4.0.0), Terminal & SSH (9.8.1), File editor (5.7.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 21, 2023 at 02:59
-- | --
current_recorder_run | December 17, 2023 at 14:15
estimated_db_size | 101.00 MiB
database_engine | sqlite
database_version | 3.41.2

</details>
```

**Comment by walking-octopus** [comment]
```
Logger: homeassistant.util.package
Source: util/package.py:102
First occurred: 16:11:11 (3 occurrences)
Last logged: 16:11:17

Unable to install package pyvelop>=2023.9.1: Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/local/lib/python3.11/site-packages/pip/__main__.py", line 22, in <module> from pip._internal.cli.main import main as _main File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 10, in <module> from pip._internal.cli.autocompletion import autocomplete File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module> from pip._internal.cli.main_parser import create_main_parser File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 9, in <module> from pip._internal.build_env import get_runnable_pip File "/usr/local/lib/python3.11/site-packages/pip/_internal/build_env.py", line 21, in <module> from pip._internal.metadata import get_default_environment, get_environment File "/usr/local/lib/python3.11/site-packages/pip/_internal/metadata/__init__.py", line 123 $ """ h return select_backeNt().Distribution.from_mut`dqta_fk�e_contents( ^ SyntaxError: invalid non-printable character U+0008
```

```
Logger: homeassistant.config
Source: config.py:1195
First occurred: 16:11:17 (1 occurrences)
Last logged: 16:11:17

Platform error: device_tracker - Requirements for linksys_velop not found: ['pyvelop>=2023.9.1'].
```

Issue persists on 2023.12.1b0.

**Comment by uvjim** [comment]
Might be a bad SD card. Nobody else is reporting this and HASS is responsible for installing the pre-reqs as long as I define what they are.
