### ISSUE TITLE
Error setting up integration (2024.1.0)

### ISSUE THREAD

**Issue by pantherale0** [uvjim/linksys_velop#446]
Hi,

Thanks for this integration, updated to HA 2024.1.0 however the integration now fails to setup:

```
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 00:28:25 (4 occurrences)
Last logged: 00:28:25

Unexpected exception importing platform custom_components.linksys_velop.binary_sensor
Unexpected exception importing platform custom_components.linksys_velop.select
Unexpected exception importing platform custom_components.linksys_velop.sensor
Unexpected exception importing platform custom_components.linksys_velop.switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/linksys_velop/binary_sensor.py", line 67, in <module>
    @dataclasses.dataclass
     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
```

```
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 00:28:25 (4 occurrences)
Last logged: 00:28:25

Unable to prepare setup for platform 'linksys_velop.binary_sensor': Platform not found (Exception importing custom_components.linksys_velop.binary_sensor).
Unable to prepare setup for platform 'linksys_velop.select': Platform not found (Exception importing custom_components.linksys_velop.select).
Unable to prepare setup for platform 'linksys_velop.sensor': Platform not found (Exception importing custom_components.linksys_velop.sensor).
Unable to prepare setup for platform 'linksys_velop.switch': Platform not found (Exception importing custom_components.linksys_velop.switch).
```

No other errors in the logs apart from the above ones

**Comment by uvjim** [comment]
Please ensure that you are using at least version `2024.1.1` of this integration. This was seized and released earlier this week.

**Comment by pantherale0** [comment]
Yep, that'll do it.

I had to manually redownload it in hacs as the update wasn't actually showing.
