### ISSUE TITLE
Errors/Warnings in log

### ISSUE THREAD

**Issue by uvjim** [uvjim/linksys_velop#467]
The following were seen in the logs after updating to HASS 2024.5.2

```
Logger: homeassistant.util.logging
Source: util/logging.py:98
First occurred: 16:59:58 (22 occurrences)
Last logged: 16:59:58

Exception in _update_device_id when dispatching 'linksys_velop_update_placeholder_ui_device': ('66e72a00-a11c-49b2-8b1b-6ac8ce48ed7a',) Traceback (most recent call last): File "/config/custom_components/linksys_velop/__init__.py", line 765, in _update_device_id self._handle_coordinator_update() File "/config/custom_components/linksys_velop/__init__.py", line 760, in _handle_coordinator_update super()._handle_coordinator_update() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'linksys_velop' calls async_write_ha_state from a thread at custom_components/linksys_velop/__init__.py, line 760: super()._handle_coordinator_update(). Please report it to the author of the 'linksys_velop' custom integration.
Exception in _get_value when dispatching 'linksys_velop_update_placeholder_ui_device': ('66e72a00-a11c-49b2-8b1b-6ac8ce48ed7a',) Traceback (most recent call last): File "/config/custom_components/linksys_velop/switch.py", line 261, in _get_value self._update_device_id(device_id=device_id) File "/config/custom_components/linksys_velop/__init__.py", line 765, in _update_device_id self._handle_coordinator_update() File "/config/custom_components/linksys_velop/switch.py", line 271, in _handle_coordinator_update super()._handle_coordinator_update() File "/config/custom_components/linksys_velop/__init__.py", line 760, in _handle_coordinator_update super()._handle_coordinator_update() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'linksys_velop' calls async_write_ha_state from a thread at custom_components/linksys_velop/__init__.py, line 760: super()._handle_coordinator_update(). Please report it to the author of the 'linksys_velop' custom integration.
Exception in _update_device_id when dispatching 'linksys_velop_update_placeholder_ui_device': ('66e72a00-a11c-49b2-8b1b-6ac8ce48ed7a',) Traceback (most recent call last): File "/config/custom_components/linksys_velop/__init__.py", line 765, in _update_device_id self._handle_coordinator_update() File "/config/custom_components/linksys_velop/switch.py", line 271, in _handle_coordinator_update super()._handle_coordinator_update() File "/config/custom_components/linksys_velop/__init__.py", line 760, in _handle_coordinator_update super()._handle_coordinator_update() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state self.hass.verify_event_loop_thread("async_write_ha_state") File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread frame.report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'linksys_velop' calls async_write_ha_state from a thread at custom_components/linksys_velop/__init__.py, line 760: super()._handle_coordinator_update(). Please report it to the author of the 'linksys_velop' custom integration.
```

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 16:59:58 (22 occurrences)
Last logged: 16:59:58

Detected that custom integration 'linksys_velop' calls async_write_ha_state from a thread at custom_components/linksys_velop/__init__.py, line 760: super()._handle_coordinator_update(), please report it to the author of the 'linksys_velop' custom integration
```

**Comment by uvjim** [comment]
All solved in local working code.
