### ISSUE TITLE
Unexpected error fetching linksys_velop speedtest

### ISSUE THREAD

**Issue by gnulabis** [uvjim/linksys_velop#517]
Hello, this is probably similar to #511.

In my case this is a Linksys WHW03v2 running firmware 2.1.19.215389. The error I see in the log is:

```
2024-11-23 22:54:55.595 ERROR (MainThread) [custom_components.linksys_velop] Unexpected error fetching linksys_velop speedtest (20J20M37A19132) data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linksys_velop/coordinator.py", line 412, in _async_update_data
    result: dict[str, Any] = responses[0][0]
                             ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Is this something that can be fixed?

Many thanks in advance!

**Comment by uvjim** [comment]
It looks exactly the same at first glance. Have you tried installing the latest beta to see if that resolves the problem for you?

**Comment by uvjim** [comment]
No problem. All devices are treated the same. A change went in recently to establish what capabilities the mesh has before creating/removing the entities in HA as appropriate.

So far, my understanding is that all Linksys Velop systems use JNAP, so 🤞 it should just work.

I believe there are some anomalies when in bridged mode mind you.
