### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by gndenton** [uvjim/linksys_velop#521]
Executed the updates to both HA and the Velop integration, but the outcome was not positive:
![image](https://github.com/user-attachments/assets/c7ca1aea-f2d6-42c9-86ae-66f9de489b10)

I am attaching a recent log file.
[home-assistant-log-26Nov2024.log](https://github.com/user-attachments/files/17961707/home-assistant-log-26Nov2024.log)

Looking for next steps.

Thanks!

**Comment by uvjim** [comment]
There's nothing in the log file mentioning this integration (apart from the initial warning by core).

Could you enable debug logging please and send a new log file?

**Comment by uvjim** [comment]
Yes. It's in the readme. You'll need to restart Home Assistant once you've put the logging settings in.

**Comment by uvjim** [comment]
It'll take me a while to go through. Looks like debug was enabled system wide. 🐻 with.

**Comment by uvjim** [comment]
Found this in the log which is raised and displayed in the newer versions of the integration...  Could you confirm if it appears in the `Settings -> System -> Logs` screen please (I'm hoping it does)?

```
custom_components.linksys_velop.exceptions.GeneralMeshTimeout: Timeout initialising the mesh (current timeout: 10.0s), consider increasing the timeout and reloading the integration
```

Could you try removing the integration and re-adding it.  The entity IDs and unique IDs should stay the same, unless you started off on a really old version of the integration, in which case the entity IDs might change.  I increased the timeout in recent versions to cope with others that had mentioned issues.

You could edit the config files directly if you know how to, so that you can change the timeout from 10 seconds.

P.S. don't forget to turn off debugging (if you haven't already).  That will also need a restart.

**Comment by gndenton** [comment]
I checked the log as requested and did not see "custom_components.linksys_velop.exceptions.GeneralMeshTimeout: Timeout initialising the mesh (current timeout: 10.0s), consider increasing the timeout and reloading the integration"

I will remove the integration and will re-add it.  I don't trust myself with editing key files.

I have already adjusted the debugging.


________________________________

**Comment by gndenton** [comment]
I removed Linksys Velop from HA; re-added the integration and got this error:
[cid:4f521674-e903-45e7-874c-ced60db0a52d]

Attaching the log file.



________________________________

**Comment by uvjim** [comment]
The attachment hasn't come through...

**Comment by gndenton** [comment]
Gary N. Denton

________________________________

**Comment by gndenton** [comment]
Trying again



Gary N. Denton



________________________________

**Comment by uvjim** [comment]
Nope. Just got your name that time.

**Comment by gndenton** [comment]
Perhaps this time.
________________________________

**Comment by uvjim** [comment]
Fraid not.

**Comment by gndenton** [comment]
> Nope. Just got your name that time.

[home-assistant-log-29Nov2024B.log](https://github.com/user-attachments/files/17962787/home-assistant-log-29Nov2024B.log)

**Comment by uvjim** [comment]
I'm not sure if it'll help, but I did notice a couple of things that needed to be resolved in your last log.  I have released `2024.12.1b1` which addresses those and increased the timeout just for the time.

Could you remove the integration (if it is indeed there) and try again after installing this beta please?  You'll need to ensure that HACS is allowing pre-releases.

If we need more logs, could you ensure that only the `linksys_velop` and `pyvelop` components are set to debug. The logs are quite long when all components are set to debug and it takes a while to find the errors/warnings.

**Comment by gndenton** [comment]
Beta version installed:
![Screenshot from 2024-12-01 10-19-04](https://github.com/user-attachments/assets/8105a271-105b-4ff1-b173-32fcc7b22663)

Log file:
[home-assistant-log-01Dec2024.log](https://github.com/user-attachments/files/17969388/home-assistant-log-01Dec2024.log)

**Comment by uvjim** [comment]
Oooo. Just like the other person... You seem a step further forward now... Are you supposed to have 2 entries?

Anyway, one thing to try now is to hit configure on one of them, increase the API timeout from 15 seconds (default) to say 60 seconds. Follow the rest of the prompts to save it. Then either reload the integration or restart Home Assistant. If that works, then I really need to find a way of speeding things up.

**Comment by gndenton** [comment]
Strangest thing.  After getting your latest note, I tried moving the timer from 15 to 60, but got another error,  So, I restarted HA for a third time and have this:
![image](https://github.com/user-attachments/assets/a7406bb0-e1c9-43fd-94ea-4f761c1d50eb) (I had deleted the second Mesh before taking the screenshot).

Let me check things out and get back to you.

**Comment by uvjim** [comment]
Hmmm... That doesn't look quite right at the moment. I'd expect 2 devices, the Mesh and the node. You'd have entities for all those then.

I think there's definitely a timing issue somewhere, that only seems to affect a few people.

I'll try and see if I can speed things up a bit. Might not happen today though.

**Comment by uvjim** [comment]
`2024.12.1b3` is now out.  I've had a stab at speeding up the initialisation routines.  I'm not sure if it'll help - I hope it will.  There is still some tidy up to do in other areas so that it fits in with these changes but 🤞 this helps.

**Comment by gndenton** [comment]
Installed, but no real progress.  The initial setup ran to "completion", but the result was nojoy.
![image](https://github.com/user-attachments/assets/c89ee12a-a8ba-4f66-a6f6-cfd7bd56c854)

Log file (sorry for the size)
[home-assistant-log-01Dec2024B.log](https://github.com/user-attachments/files/17970040/home-assistant-log-01Dec2024B.log)

**Comment by uvjim** [comment]
Did you try changing the timeout in the configure option and then reloading?

**Comment by uvjim** [comment]
As a benchmark from my system (3 x MX4200 and approximately 70 devices; a mixture of offline and online ones) without debugging for `pyvelop` enabled I can see the following: -

```
2024-12-01 19:28:32.341 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_ssdp --> entered, discovery_info: SsdpServiceInfo(ssdp_usn='uuid:ebf5a0a0-1dd1-11b2-a90f-e89f8060c837::urn:schemas-upnp-org:device:InternetGatewayDevice:2', ssdp_st='urn:schemas-upnp-org:device:InternetGatewayDevice:2', upnp={'X_hardwareId': 'VEN_0BD5&DEV_0002&REV_01 VEN_0033&DEV_0008&REV_01', 'X_deviceCategory': ['NetworkInfrastructure.Router NetworkInfrastructure.AccessPoint', 'Network.Router.Wireless'], 'X_modelId': '6B54C6A6-21E3-4a55-9D7C-39DB318DEE73', 'deviceType': 'urn:schemas-upnp-org:device:InternetGatewayDevice:2', 'friendlyName': 'router', 'manufacturer': 'Linksys', 'manufacturerURL': 'http://www.linksys.com', 'modelDescription': 'Velop AX4200 WiFi 6 System', 'modelName': 'MX42', 'modelNumber': 'MX42', 'modelURL': 'http://www.linksys.com', 'serialNumber': '38U10M3BA40594', 'UDN': 'uuid:ebf5a0a0-1dd1-11b2-a90f-e89f8060c837', 'UPC': '012345678910', 'serviceList': {'service': {'serviceType': 'urn:schemas-upnp-org:service:Layer3Forwarding:1', 'serviceId': 'urn:upnp-org:serviceId:L3Forwarding1', 'SCPDURL': '/Layer3ForwardingSCPD.xml', 'controlURL': '/upnp/control/Layer3Forwarding', 'eventSubURL': '/upnp/event/Layer3Forwarding'}}, 'deviceList': {'device': {'deviceType': 'urn:schemas-upnp-org:device:WANDevice:2', 'friendlyName': 'WANDevice:2', 'manufacturer': 'Linksys', 'manufacturerURL': 'http://www.linksys.com', 'modelDescription': 'Velop AX4200 WiFi 6 System', 'modelName': 'MX42', 'modelNumber': 'MX42', 'modelURL': 'http://www.linksys.com', 'serialNumber': '38U10M3BA40594', 'UDN': 'uuid:ebf5a0a0-1dd1-11b2-a91f-e89f8060c837', 'UPC': '012345678910', 'serviceList': {'service': {'serviceType': 'urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1', 'serviceId': 'urn:upnp-org:serviceId:WANCommonIFC1', 'SCPDURL': '/WANCommonInterfaceConfigSCPD.xml', 'controlURL': '/upnp/control/WANCommonInterfaceConfig0', 'eventSubURL': '/upnp/event/WANCommonInterfaceConfig0'}}, 'deviceList': {'device': {'deviceType': 'urn:schemas-upnp-org:device:WANConnectionDevice:2', 'friendlyName': 'WANConnectionDevice:2', 'manufacturer': 'Linksys', 'manufacturerURL': 'http://www.linksys.com', 'modelDescription': 'Velop AX4200 WiFi 6 System', 'modelName': 'MX42', 'modelNumber': 'MX42', 'modelURL': 'http://www.linksys.com', 'serialNumber': '38U10M3BA40594', 'UDN': 'uuid:ebf5a0a0-1dd1-11b2-a92f-e89f8060c837', 'UPC': '012345678910', 'serviceList': {'service': [{'serviceType': 'urn:schemas-upnp-org:service:WANIPConnection:2', 'serviceId': 'urn:upnp-org:serviceId:WANIPConn1', 'SCPDURL': '/WANIPConnectionServiceSCPD.xml', 'controlURL': '/upnp/control/WANIPConnection0', 'eventSubURL': '/upnp/event/WANIPConnection0'}, {'serviceType': 'urn:schemas-upnp-org:service:WANEthernetLinkConfig:1', 'serviceId': 'urn:upnp-org:serviceId:WANEthLinkC1', 'SCPDURL': '/WANEthernetLinkConfigSCPD.xml', 'controlURL': '/upnp/control/WANEthernetLinkConfig0', 'eventSubURL': '/upnp/event/WANEthernetLinkConfig0'}]}, 'presentationURL': '/index.asp'}}}}, 'presentationURL': 'http://MX42-EU.home.linksys.com'}, ssdp_location='http://192.168.1.254:49152/IGDdevicedesc.xml', ssdp_nt=None, ssdp_udn='uuid:ebf5a0a0-1dd1-11b2-a90f-e89f8060c837', ssdp_ext='', ssdp_server='Linux/4.4.60, UPnP/1.0, Portable SDK for UPnP devices/1.6.19', ssdp_headers={'CACHE-CONTROL': 'max-age=1800', 'DATE': 'Sun, 01 Dec 2024 19:28:29 GMT', 'EXT': '', 'LOCATION': 'http://192.168.1.254:49152/IGDdevicedesc.xml', 'OPT': '"http://schemas.upnp.org/upnp/1/0/"; ns=01', '01-NLS': '85770aa0-1dd2-11b2-8c11-b7392fe60a18', 'SERVER': 'Linux/4.4.60, UPnP/1.0, Portable SDK for UPnP devices/1.6.19', 'X-User-Agent': 'redsonic', 'ST': 'urn:schemas-upnp-org:device:InternetGatewayDevice:2', 'USN': 'uuid:ebf5a0a0-1dd1-11b2-a90f-e89f8060c837::urn:schemas-upnp-org:device:InternetGatewayDevice:2', '_host': '192.168.1.254', '_udn': 'uuid:ebf5a0a0-1dd1-11b2-a90f-e89f8060c837', '_location_original': 'http://192.168.1.254:49152/IGDdevicedesc.xml', 'location': 'http://192.168.1.254:49152/IGDdevicedesc.xml', '_timestamp': datetime.datetime(2024, 12, 1, 19, 28, 29, 4621), '_remote_addr': ('192.168.1.254', 49456), '_port': 49456, '_local_addr': ('0.0.0.0', 0), '_source': <SsdpSource.SEARCH: 'search'>}, ssdp_all_locations={'http://192.168.1.254:49152/IGDdevicedesc.xml'}, x_homeassistant_matching_domains={'linksys_velop', 'upnp'})
2024-12-01 19:28:32.396 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_ssdp --> setting unique_id
2024-12-01 19:28:32.428 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_user --> entered, user_input: None
2024-12-01 19:28:34.482 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_user --> entered, user_input: None
2024-12-01 19:28:37.425 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_user --> entered, user_input: {'node': '192.168.1.254', 'password': '**REDACTED**'}
2024-12-01 19:28:37.465 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_login --> entered, user_input: None
2024-12-01 19:28:37.500 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_login --> creating credential test task
2024-12-01 19:28:37.534 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> entered, details: {'node': '192.168.1.254', 'password': '**REDACTED**', 'request_timeout': 60}
2024-12-01 19:28:37.720 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> testing credentials
2024-12-01 19:28:38.204 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> credentials tested
2024-12-01 19:28:38.232 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> credentials are valid
2024-12-01 19:28:38.260 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> no exceptions
2024-12-01 19:28:38.289 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_login --> exited
2024-12-01 19:28:38.318 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_login --> entered, user_input: None
2024-12-01 19:28:38.347 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_login --> _errors: {}
2024-12-01 19:28:38.375 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_login --> next step: gather_details
2024-12-01 19:28:38.560 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_gather_details --> entered, user_input: None
2024-12-01 19:28:38.590 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_gather_details --> creating task for gathering details
2024-12-01 19:28:38.622 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_gather_details --> entered
2024-12-01 19:28:45.603 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_gather_details --> no exceptions
2024-12-01 19:28:45.637 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] _async_task_gather_details --> exited
2024-12-01 19:28:45.674 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_gather_details --> entered, user_input: None
2024-12-01 19:28:45.702 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_gather_details --> _errors: {}
2024-12-01 19:28:45.731 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_gather_details --> next step: timers
2024-12-01 19:28:45.781 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_timers --> entered, user_input: None
2024-12-01 19:28:49.730 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_timers --> entered, user_input: {'scan_interval': 60.0, 'scan_interval_device_tracker': 10.0, 'consider_home': 180.0, 'api_request_timeout': 15.0}
2024-12-01 19:28:49.761 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_device_trackers --> entered, user_input: None
2024-12-01 19:28:53.557 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_device_trackers --> entered, user_input: {'tracked': []}
2024-12-01 19:28:53.599 DEBUG (MainThread) [custom_components.linksys_velop.config_flow] async_step_finish --> entered
2024-12-01 19:28:53.638 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> entered
2024-12-01 19:28:53.672 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> setting up Mesh for the coordinator
2024-12-01 19:29:02.169 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> setting up the mesh coordinator
2024-12-01 19:29:04.557 DEBUG (MainThread) [custom_components.linksys_velop] Finished fetching linksys_velop mesh (38U10M3BA40594) data in 2.388 seconds (success: True)
2024-12-01 19:29:04.586 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> setting up the speedtest coordinator
2024-12-01 19:29:05.388 DEBUG (MainThread) [custom_components.linksys_velop] Finished fetching linksys_velop speedtest (38U10M3BA40594) data in 0.802 seconds (success: True)
2024-12-01 19:29:05.417 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> setting up the channel scan coordinator
2024-12-01 19:29:05.939 DEBUG (MainThread) [custom_components.linksys_velop] Finished fetching linksys_velop channel scan (38U10M3BA40594) data in 0.521 seconds (success: True)
2024-12-01 19:29:05.968 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> setting up platforms: ['binary_sensor', 'button', 'sensor', 'switch', 'update', 'event']
2024-12-01 19:29:06.290 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> cleaning up ui devices
2024-12-01 19:29:06.321 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> cleaning up device trackers
2024-12-01 19:29:06.352 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> registering services
2024-12-01 19:29:06.382 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> listening for config changes
2024-12-01 19:29:06.411 DEBUG (MainThread) [custom_components.linksys_velop] async_setup_entry (38U10M3BA40594) --> exited
```

That's from start to end of adding the integration on my test Home Assistant system (only has 3 custom integrations loaded - all written by me).

It takes about 1 second to verify the password.
Just over 7 seconds to gather details, which essentially retrieves the Mesh capabilities and gathers all the information.
It's then approximately 2 seconds per poll for data from the Mesh.  If Channel Scan or Speedtest functionality is available the data for those is gathered once and then only if the entities are enabled.

**Comment by gndenton** [comment]
Where and How do I edit the two values you suggest? I am a newbie in this space.

With regards to the end-to-end timing, what changed in the HA release and the Linksys_Velop release which is causing the delay?  My hardware hasn't changed, so I would look beyond those items.  Perhaps my HA is heavy and this is what is causing the failure.

**Comment by uvjim** [comment]
In your last screenshot, click configure, set the API timeout (last in the list IIRC, currently set to 15).  Set it to 45 seconds (because I guess you don't want it to be constantly polling if the timeouts are almost the same as the poll period). Then follow the on-screen prompts, it'll then probably fail again, but reload the integration (3 dots on the right in your screenshot) and it should kick to life.

RE: changes... I introduced the ability to send queries out to the Mesh and establish what functionality it has based on the known queries for gathering data.  It then uses this to create/delete the entities that your Mesh does/doesn't support, as appropriate.

Each Mesh poll will then only send requests for what is supported and enabled.

For some reason, this seems to be causing issues for some setups; I have no idea why because the only result seems to be a timeout.  I've bumped it once (from 10 secs to 15 secs).  I've split the config timeout from the BAU timeout - config one is 60 secs and the BAU uses the API timeout you specify.

I have no issues with the smaller timeouts on my production environment either, which has much more running on it.

I don't know what has changed in HA releases because as long as it doesn't break what I'm running and testing against, or doesn't generate warnings then I leave it at that.  I just then react to issues that people send over.

**Comment by gndenton** [comment]
Change on timer resulted in "Unknown Error".  Reloaded, but the result was the same.

[home-assistant-log-01Dec2024C.log](https://github.com/user-attachments/files/17970218/home-assistant-log-01Dec2024C.log)

Thanks for the details.  I may try to reboot the mesh tomorrow AM since "a reboot can improve performance".

**Comment by uvjim** [comment]
Probably a plan. A reboot solves the world's ills.

**Comment by gndenton** [comment]
Restarted the mesh this AM.
Deleted the integration
Added the integration
After credentials, on the timers screen, I changed the 15 to 45
Result:
![image](https://github.com/user-attachments/assets/30f11080-2e03-476e-a52d-b7c5f431614c)

[home-assistant-log-02Dec2024.log](https://github.com/user-attachments/files/17978941/home-assistant-log-02Dec2024.log)

**Comment by gndenton** [comment]
So, on a whim, I tried to configure the settings again (before I got your last note) and l and behold, setup completed and things look normal:
![image](https://github.com/user-attachments/assets/9eaee15b-2172-46cb-8a74-00bb34d68a22)

I'm going to leave it be!  Thanks for the time and education.  Do you want to close this. or wait for a standard release?

**Comment by uvjim** [comment]
Let's wait for a bit.  We can leave this hanging. 😆 
Glad it's working finally.

**Comment by webwude** [comment]
Installed the latest HA Version core 2024.12.1.

Now I get the error: 

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 21:13:54 (1 Vorkommnisse)
Zuletzt protokolliert: 21:13:54

Setup failed for custom integration 'linksys_velop': Unable to import component: cannot import name 'entity_registry' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/linksys_velop/__init__.py", line 10, in <module>
    from homeassistant.config_entries import entity_registry as er
ImportError: cannot import name 'entity_registry' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/linksys_velop/__init__.py", line 10, in <module>
    from homeassistant.config_entries import entity_registry as er
ImportError: cannot import name 'entity_registry' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)

Integration is not loaded. Using the latest release. No beta yet.
