### ISSUE TITLE
Still Not Working

### ISSUE THREAD

**Issue by wormuths** [uvjim/linksys_velop#546]
I am now up to Home Assistant 2024.12.3 and the latest version of this integration, 2024.12.1.  The two separate mesh nodes I have (one with two nodes, 1 with 4 nodes), neither will initialize.  Here are the log errors.

```
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 10:14:28 PM (3 occurrences)
Last logged: 10:15:41 PM

Error setting up entry Linksys Velop Mesh for linksys_velop
Traceback (most recent call last):
  File "/config/custom_components/linksys_velop/__init__.py", line 137, in async_setup_entry
    await mesh.async_initialise()
  File "/usr/local/lib/python3.13/site-packages/pyvelop/mesh.py", line 799, in async_initialise
    await self.async_detect_capabilities()
  File "/usr/local/lib/python3.13/site-packages/pyvelop/mesh.py", line 561, in async_detect_capabilities
    responses: list[tuple[api.Request, api.Response]] = await asyncio.gather(
                                                        ^^^^^^^^^^^^^^^^^^^^^
        *requests
        ^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pyvelop/mesh.py", line 279, in _async_make_request
    raise err from None
  File "/usr/local/lib/python3.13/site-packages/pyvelop/mesh.py", line 277, in _async_make_request
    req_resp = await req.execute(timeout=self._timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyvelop/jnap.py", line 192, in execute
    raise MeshTimeoutError from err
pyvelop.exceptions.MeshTimeoutError: Timeout Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linksys_velop/__init__.py", line 149, in async_setup_entry
    raise exc_mesh_timeout from exc
custom_components.linksys_velop.exceptions.GeneralMeshTimeout: Timeout initialising the mesh (current timeout: 10.0s), consider increasing the timeout and reloading the integration
```

Hopefully we can get this solved.  I was on a 2024.9.x version of this integration and the last version of Home Assistant 2024.11.3 and it worked.

**Comment by uvjim** [comment]
As per the traceback, have you tried increasing the timeout and reloading the integration?

It appears that your API timeout is set to 10s which doesn't seem enough for some environments. The new default is 15s, and even that had an issue in one reported environment.

**Comment by madtraxx18** [comment]
Where can we change the api time-out? I’m having exact the same issues (all version above 2024.10.1)

**Comment by uvjim** [comment]
@wormuths I'm assuming as you've raised #550 that this can be closed now?
